In [2]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt 
import seaborn as sns

In [5]:
data = {
    "name" : ["Falcon Heavy", "Falcon 9", "Starship Super Heavy", "Dragon"],
    "flights" : [11, 600,11,30],
    "rating" : [4,5,3,3]
}

df = pd.DataFrame(data=data)
df

                   name  flights  rating
0          Falcon Heavy       11       4
1              Falcon 9      600       5
2  Starship Super Heavy       11       3
3                Dragon       30       3

In [7]:
df.head() # prints first 5 rows

                   name  flights  rating
0          Falcon Heavy       11       4
1              Falcon 9      600       5
2  Starship Super Heavy       11       3
3                Dragon       30       3

In [9]:
df.info() # prints the data types for all columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     4 non-null      object
 1   flights  4 non-null      int64
 2   rating   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [ ]:
df.describe() # gives stats for numerical cols

          flights    rating
count    4.000000  4.000000
mean   163.000000  3.750000
std    291.470982  0.957427
min     11.000000  3.000000
25%     11.000000  3.000000
50%     20.500000  3.500000
75%    172.500000  4.250000
max    600.000000  5.000000